name = "rs-worker"
main = "build/index.js"
compatibility_date = "2026-04-03"

[build]
command = "cargo install -q \"worker-build@^0.7\" && worker-build --release"

[[d1_databases]]
binding = "DB"
database_name = "campfire-db"
database_id = "72703a55-3570-48db-9f1b-37b0a3fc8329"
